/**
 * Site Configuration — Adi's Ceramics
 * Central config object consumed by script.js for dynamic content injection.
 * Generated by Page Builder agent.
 */

/* eslint-disable no-unused-vars */
var SITE_CONFIG = {
  siteName: "Adi's Ceramics",
  tagline: "Shaped by hand. Fired with intention.",

  meta: {
    title: "Adi\u2019s Ceramics \u2014 Handcrafted Ceramic Art",
    description:
      "Explore the handcrafted ceramic art of Adi \u2014 earthy, sculptural pieces made with care. View the gallery and get in touch.",
    author: "Adi"
  },

  navLinks: [
    { label: "Gallery", href: "#gallery" },
    { label: "About", href: "#about" },
    { label: "Contact", href: "#contact" }
  ],

  hero: {
    headline: "Adi\u2019s Ceramics",
    subheadline: "Shaped by hand. Fired with intention."
  },

  gallery: {
    images: [
      "547b7b08-6024-4f80-806c-924dcc5532c5.jpg",
      "IMG_0100.JPG",
      "IMG_0106.jpg",
      "IMG_0110.JPG",
      "IMG_0895.jpg",
      "IMG_0899.JPG",
      "IMG_1102.jpg",
      "IMG_1111.jpg",
      "IMG_2231.JPG",
      "IMG_2232.jpg",
      "IMG_2233.JPG",
      "IMG_2234.JPG",
      "IMG_2235.JPG",
      "IMG_4287.JPG",
      "IMG_4399.JPG",
      "IMG_4540.JPG",
      "IMG_4577.JPG",
      "IMG_4594.jpg",
      "IMG_4601.jpg",
      "IMG_4603.jpg",
      "IMG_4604.jpg",
      "IMG_4605.jpg",
      "IMG_4606.jpg",
      "IMG_4609.jpg",
      "IMG_4612.jpg",
      "IMG_4614.jpg",
      "IMG_4617.jpg",
      "IMG_4618.jpg",
      "IMG_4640.JPG",
      "IMG_4646.JPG",
      "IMG_4650.JPG",
      "IMG_4652.JPG",
      "IMG_4655.JPG",
      "IMG_5925.JPG",
      "IMG_5929.jpg",
      "IMG_6021.JPG",
      "IMG_6662.JPG",
      "IMG_6788.jpg",
      "IMG_7555.JPG",
      "IMG_7562.jpg",
      "IMG_7564.jpg",
      "IMG_8257.jpg",
      "IMG_8651.jpg",
      "IMG_8654.JPG",
      "IMG_8706.jpg",
      "IMG_8708.JPG",
      "IMG_8796.JPG",
      "IMG_9305.jpg",
      "IMG_9308.jpg",
      "IMG_9932.jpg"
    ],
    basePath: "assets/images/"
  },

  about: {
    heading: "About Adi",
    body: "Every piece begins as a lump of earth and a quiet idea. Adi works with stoneware and porcelain in a small studio filled with natural light, shaping each vessel by hand on the wheel or through patient coil-building. There is no rush here \u2014 only the slow conversation between hands and clay, glaze and flame. The results are objects meant to be touched, held, and lived with \u2014 bowls that cradle your morning coffee, vases that lean slightly because perfection was never the point."
  },

  contact: {
    email: "shadmi89@gmail.com",
    formAction: ""
  },

  social: {},

  footer: {
    copyright: "\u00A9 " + new Date().getFullYear() + " Adi\u2019s Ceramics",
    builtWith: "Handcrafted with clay & code"
  }
};
